### ISSUE TITLE
Docker - Where should the prometheus config go?

### ISSUE THREAD

**Issue by Jojonintendo** [crowdsecurity/grafana-dashboards#19]
I have a containerized setup with two containers: crowdsec and grafana.

Crowdsec is working correctly, and Grafana is listening to CS container on port 6060. As per the dashboard, the data source is working fine, and I've imported the dashboard profiles. No data is actually shown.

I can't find where to put this config (as per this repo's guide on the front page):
```
  - job_name: 'crowdsec_myMachine'
    static_configs:
    - targets: ['1.2.3.4:6060']
      labels:
        machine: 'my_machine'
```
My understanding is that it should be in the crowdsec container, but I couldn't find anything related to prometheus inside it.
Where should it be added? I'm probably missing something obvious because I've never used prometheus before, any help is appreciated.
