### ISSUE TITLE
Grafana Dashboards don't show data

### ISSUE THREAD

**Issue by johnynfulleffect** [crowdsecurity/grafana-dashboards#22]
I am using Crowdsec 1.5, but this was an issue on 1.4 as well.  I downloaded the Grafana v4 dashboards from this repo and added to my Grafana instance.  My Prom data source is setup correctly.  I have also ensured that I have a Prometheus scrape setup as follows:

```
  - job_name: 'crowdsec'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['crowdsec-service.crowdsec.svc.cluster.local:6060']
```

Testing this endpoint works and shows metrics for prometheus.  However, The dashboards are mostly blank, show NaN, or show bad data.  Some of the panels work, and the LAPI Metrics fully works, although I don't understand the units or what data it shows.

Some screen shots of what I see:

LAPI Metrics (yay! but what does it mean?)
![image](https://github.com/crowdsecurity/grafana-dashboards/assets/5731535/69c34fe2-a181-454f-a020-82309be3c59d)

Crowdsec Details per Machine
![image](https://github.com/crowdsecurity/grafana-dashboards/assets/5731535/c35b91e4-86f5-47e6-b9a9-a042ba96d6fb)

Crowdsec Insight
![image](https://github.com/crowdsecurity/grafana-dashboards/assets/5731535/34f94050-9ff1-4cc2-8f94-3bf7785d5df2)

Crowdsec Overview
![image](https://github.com/crowdsecurity/grafana-dashboards/assets/5731535/09ced472-dd11-46c0-804e-35cc509486e5)
